services:
    web:
        build: .
        ports:
            - "3000:3000"
        volumes:
            - .:/app             # Mount current dir for hot-reload
            - /app/node_modules  # Avoid overwriting node_modules inside container
        environment:
            - NODE_ENV=development
